[project]
name = 'Decentralized-Agricultural-Equipment-Sharing'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.equipment-register]
path = 'contracts/equipment-register.clar'
clarity_version = 2
epoch = 2.5

[contracts.farmer-verification]
path = 'contracts/farmer-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.intellectual-property]
path = 'contracts/intellectual-property.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
